"""<your message>

Revision ID: 5e3f79eec57d
Revises: 1a660c242acb
Create Date: 2024-01-11 21:08:04.910817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3f79eec57d'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=off")  # Disable foreign key checks for SQLite

    # Baked Goods Table
    op.execute("UPDATE baked_goods SET name = NULL WHERE name = '' OR name IS NULL")
    op.execute("PRAGMA foreign_key_list('baked_goods')")
    op.execute("PRAGMA table_info('baked_goods')")

    # Create a temporary table with the desired changes
    op.execute("""
        CREATE TABLE baked_goods_temp AS 
        SELECT * FROM baked_goods WHERE 1=0
    """)
    
    op.execute("""
        INSERT INTO baked_goods_temp (id, name, price, bakery_id) 
        SELECT id, name, CAST(price AS FLOAT), bakery_id FROM baked_goods
    """)

    # Drop the original table
    op.execute("DROP TABLE baked_goods")

    # Rename the temporary table to the original table name
    op.execute("ALTER TABLE baked_goods_temp RENAME TO baked_goods")

    # Set NOT NULL constraint for the 'name' column
    op.execute("UPDATE baked_goods SET name = 'Unknown' WHERE name IS NULL")
    op.execute("ALTER TABLE baked_goods MODIFY COLUMN name VARCHAR NOT NULL")

    # Additional modifications for other columns...

    op.execute("PRAGMA foreign_keys=on")  # Enable foreign key checks after modifications
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=off")  # Disable foreign key checks for SQLite

    # Baked Goods Table
    op.execute("UPDATE baked_goods SET name = '' WHERE name IS NULL")
    op.execute("ALTER TABLE baked_goods MODIFY COLUMN name VARCHAR")

    # Additional modifications for other columns...

    op.execute("PRAGMA foreign_keys=on")  # Enable foreign key checks after modifications
    # ### end Alembic commands ###
